### PR TITLE
Adjustments to pymmcore-integration

### PR DESCRIPTION
**Pull request by felixwanitschke**
- change device selction ui to stacked widget
- change setExposure to setProperty
- adding scrollBar to camera Settings

### CODE REVIEW

**Comment by jacopoabramo** [comment]
@felixwanitschke sometimes when changing a property an Exception is thrown due to the fact that there is probably a type mismatch between the input value (which is always a string) and the actual type of the parameter (which could be a float, int, etc). You should use `getPropertyType` and use the `PropertyType` enumerator to correctly cast the input values, and then call `setProperty`

**Comment by felixwanitschke** [comment]
Problem: Changing the properties "Bit depth", "Binning" and "PixelType" causes crashes

Problem has to do with how pymmcore changes this properties, while the continuous acquisation is running. By changing the way the properties are changed (see attached screenshot) this can be solved to some extend. However, it is still not very stable and still can cause crashes.


My changes:
image


Before: 
    image

**Review by jacopoabramo — APPROVED** [review]

**Comment by felixwanitschke** [comment]
In the version I see it is already called MicroManager? Is is different for you? Maybe I messed something up with the commit...

**Comment by jacopoabramo** [comment]
> In the version I see it is already called MicroManager? Is is different for you? Maybe I messed something up with the commit...

what are you referring to? the filename or the interface shown in the UI? looks good to me, I also updated the pypi package with a new release

**Comment by felixwanitschke** [comment]
> Change to `MicroManager`.

I was referring to this comment. But if everything is fine, everything is fine ;)

**Pull request merged**
